- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/templates/re/dind-daemon-conf.re.yaml
- charts/cf-runtime/values.yaml
Allows users of the Helm template to specify their own docker-in-docker daemon configuration by adding any valid [dockerd configuration setting](https://docs.docker.com/engine/reference/commandline/dockerd/) as fields in `re.dindDaemon`.
For example, to change the bridge IP to avoid network conflicts with the default dockerd subnet (`172.17.0.0/16`):
```yaml
re:
dindDaemon:
bip: 172.16.0.0/24
```
Any dind pods launched by the runtime will have assigned IPs in the `172.16.0.0/24` subnet and can now route to hosts on `172.17.0.0/24`.
> Customize dind daemon config via Helm

- .deploy/cf-runtime/Chart.yaml
- .deploy/cf-runtime/templates/monitor/secret.monitor.yaml
- .deploy/cf-runtime/templates/volume-provisioner/_helpers.tpl
- .deploy/cf-runtime/templates/volume-provisioner/cron-job.dind-volume-cleanup.vp.yaml
- .deploy/cf-runtime/values.yaml
- Check if monitor is enabled before creating monitor secret
- trunc volume cleanup cron name to make sure it's not more than 52 chars by k8s limit
> feat/alonbe/improve_cf_runtime_chart 

- .deploy/cf-runtime/templates/volume-provisioner/deployment.dind-volume-provisioner.vp.yaml
- .deploy/cf-runtime/values.yaml
- annotations are useful for equipping pod with extra functionality delivered externally or for auto-discovery 
- currently there's no way to add annotation to `dind volume provisioner` pod from within the helm chart
- this PR add this feature
> Add annotations to dind volume provisioner pod

- .deploy/cf-runtime/Chart.yaml
- .deploy/cf-runtime/README.md
- .deploy/cf-runtime/templates/re/service-account.re.yaml
- .deploy/cf-runtime/templates/venona/deployment.runner.yaml
- .deploy/cf-runtime/templates/volume-provisioner/service-account.dind-volume-provisioner.vp.yaml
- .deploy/cf-runtime/templates/volume-provisioner/storageclass.dind-volume-provisioner.vp.yaml
- .deploy/cf-runtime/values.yaml
Runner pod - adding optional annotations
We need a custom annotation on the pod in order to be able to collect its logs by datadog
- I tested the changes, and the same syntax is already being used [here](https://github.com/codefresh-io/venona/blob/release-1.0/.deploy/cf-runtime/templates/volume-provisioner/deployment.dind-volume-provisioner.vp.yaml#L15)
- This PR also contains alignment fixes for unrelated files
@danielm-codefresh @yaroslav-codefresh @roi-codefresh Tagging you here because you're the last ones to commit in this repo 🙏
> Runner pod - adding optional annotations

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
Remove `remove artifacthub.io/alternativeName` annotation
> fix: remove artifacthub.io/alternativeName annotation

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
- charts/cf-runtime/tests/private-registry/private_registry_test.yaml
- charts/cf-runtime/tests/values-private-registry.yaml
> fix: imageRegistry in runtime spec

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades engine to v1.167.4, adding support for `timeout` flag in pipeline steps.
—
—
> Add support for `timeout` flag in pipeline steps

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades engine to v1.168.0 which contains a fix for build memory metrics.
Exact formula depends on Control Group and Docker API versions:
* **cgroup v1**: `memoryUsage = memory_stats.usage - memory_stats.stats.total_inactive_file`
* **cgroup v2**: `memoryUsage = memory_stats.usage - memory_stats.stats.inactive_file`
* **unknown cgroup (older Docker API)**: `memoryUsage = memory_stats.usage - memory_stats.stats.cache`
Bug fix.
—
> fix(engine): exclude inactive memory from memory metrics

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades `engine` to v1.168.2 with fixes to memory and CPU metrics for cgroup v2.
Bug fix.
—
> build: upgrade `engine` to v1.168.2

- charts/cf-runtime/.ci/values-ci.yaml
- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
- charts/cf-runtime/tests/runtime/runtime_values.yaml
- charts/cf-runtime/values.yaml
> feat(cf-runtime): add labels to dind/engine pods

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades an `engine` to v1.169.0, which adds support for `strict_fail_fast` field in pipeline yaml.
New feature development.
—
> feat(engine): add support for `strict_fail_fast` field in pipelines

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades engine to v1.169.2 with new warnings if typed step was specified without or with incorrect version.
—
—
> build: upgrade engine to v1.169.2

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades engine to v1.169.3 with the following changes in pipeline YAML validation:
1. Validation for step types is disabled if there are variable(s) in the type.
2. When suggesting correct step properties, wrong property itself will be excluded from the suggestion list.
—
—
> build(engine): upgrade engine to v1.169.3

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/tests/private-registry/private_registry_test.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
- charts/cf-runtime/values.yaml
This upgrades `engine` to v1.169.7 with fix for rare memory leak in `engine` caused by delays in `container-logger`. The new version of the `engine` also adds an ability to log outgoing HTTP requests, which is disabled by default.
Bug fix.
—
> fix: fix memory leak in engine

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
> chore(chart): updated k8s-agent

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
This fixes runtime template for dind env vars.
Bug fix.
—
> fix: dind env vars

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades the `engine` and `cf-app-proxy` to the recent versions with fixes to TLS for MongoDB and Redis.
Bug fix.
—
> fix: fix TLS for MongoDB and Redis

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/_components/runner/_deployment.yaml
Fixing the init container in the runner deployment template. Removing redundent space that cause issues when using 3d tools like Vals (helmfile/vals)
There is an issue with your helm chart using 3d tools like Vals (helmfile/vals). You have an extra space which cause "mapping values are not allowed in this context" error in 3d tools reading the template result of the cf-runner helm chart.
This change fixes this bug without changing anything else.
We at Honeybook are one of your customers and this issue is a blocker to several of our tasks.
POC:
> fix(deployment-init-container): Update _deployment.yaml to support 3d tools like Vals

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/_components/runner/_deployment.yaml
- charts/cf-runtime/templates/hooks/post-install/job-gencerts-dind.yaml
- charts/cf-runtime/templates/hooks/pre-delete/job-cleanup-resources.yaml
Fixing the args of the reconcile-runtime container and the gencerts and cleanup jobs containers. Removing redundent space that cause issues when using 3d tools like Vals (helmfile/vals)
There is an issue with your helm chart using 3d tools like Vals (helmfile/vals). You have an extra space which cause "mapping values are not allowed in this context" error in 3d tools reading the template result of the cf-runner helm chart.
This change fixes this bug without changing anything else.
Not ready yet.
Sorry for creating 2 different pull requests, I didn't expect you will be that fast 💪
POC:
> fix(jobs-containers): Update deployment and jobs to support 3d tools like Vals

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
> fix(onprem): resources overrides for agentless runtime

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This fixes a bug introduced in the engine v1.169.11, which led to the output of logs in plaintext instead of JSON.
Bug fix.
—
> fix(engine): output logs in JSON

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/tests/private-registry/private_registry_test.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
- charts/cf-runtime/values.yaml
This upgrades the `engine` to the most recent version that allows to force sequential pull of compose images.
—
—
> build: upgrade `engine`

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
- charts/cf-runtime/tests/private-registry/private_registry_test.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
This fixes an issue within the RE template that resulted in the lack of certain runtime images from the engine envs.
—
—
> fix(engine): fix Runtime Images assignment

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml
- charts/cf-runtime/tests/private-registry/private_registry_test.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml
- charts/cf-runtime/tests/runtime/runtime_onprem_values.yaml
- charts/cf-runtime/tests/runtime/runtime_test.yaml
- charts/cf-runtime/tests/runtime/runtime_values.yaml
Strings are currently not quoted in the envVars sections for engine and dind pods in the helm chart. This is an issue if you put an env value in that is actually an integer or a float but put quotes around it. The helm chart will think it's a string and so leave the value unquoted which will then cause issues when the yaml is parsed inside the runner (in venona's go code).
Env vars are always strings so we can wrap them all in quotes no matter what type they are. I've removed the type checking code for this reason.
Jira: https://codefresh-io.atlassian.net/browse/CR-25435
> fix: ensure all env var values are quoted

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/README.md.gotmpl
> feat: image digest

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
> fix: misc security update

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
This upgrades `venona` to the most recent version with improvements to resource cleanup after build finish.
> build: upgrade `venona`

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
> fix: revert cf-app-proxy

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/values.yaml
> chore(CR-29161): updated cf-app-proxy

- charts/cf-runtime/Chart.yaml
- charts/cf-runtime/README.md
- charts/cf-runtime/templates/runtime/svc-dind.yaml
> feat: add ports for dind headless service
