README.md, venonactl/cmd/install.go
@olegsu Clarification on Install options for Venona
=> added install options to readme and clarification to cluster-name option

venonactl/cmd/install-app-proxy.go, venonactl/cmd/install-monitor.go, venonactl/example/values-example.yaml, venonactl/pkg/plugins/app-proxy.go, venonactl/pkg/store/store.go, venonactl/pkg/templates/kubernetes/cluster-role-binding.app-proxy.yaml, venonactl/pkg/templates/kubernetes/daemonset.dind-lv-monitor.vp.yaml, venonactl/pkg/templates/kubernetes/deployment.app-proxy.yaml, venonactl/pkg/templates/kubernetes/deployment.dind-volume-provisioner.vp.yaml, venonactl/pkg/templates/kubernetes/deployment.monitor.yaml, venonactl/pkg/templates/kubernetes/deployment.venona.yaml, venonactl/pkg/templates/kubernetes/ingress.app-proxy.yaml, venonactl/pkg/templates/kubernetes/rollback-serviceaccount.monitor.yaml, venonactl/pkg/templates/kubernetes/service-account.app-proxy.yaml, venonactl/pkg/templates/kubernetes/service-account.dind-volume-provisioner.vp.yaml, venonactl/pkg/templates/kubernetes/service-account.engine.yaml, venonactl/pkg/templates/kubernetes/service-account.monitor.yaml, venonactl/pkg/templates/kubernetes/service.app-proxy.yaml, venonactl/pkg/templates/kubernetes/storageclass.dind-volume-provisioner.vp.yaml, venonactl/pkg/templates/kubernetes/templates.go
* now you can control service account annotations for each service account
=> improved values yaml

venonactl/.goreleaser.yml
=> remove prerelease tag

charts/cf-runtime/Chart.yaml, charts/cf-runtime/templates/volume-provisioner/deployment.dind-volume-provisioner.vp.yaml, charts/cf-runtime/values.yaml
Refactored volume-provisioner template and values
*related to the issue described in CR-7970
=> [CR-7970] upd cf-runtime chart

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/tests/runtime/runtime_test.yaml, charts/cf-runtime/tests/runtime/runtime_values.yaml, charts/cf-runtime/values.yaml
=> feat: empty dind requests

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> feat: run ci on rootless dind

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl
=> docs: fix mandatory token note

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/other/extra-resources.yaml, charts/cf-runtime/values.yaml
=> feat: add extraResources

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md
=> feat: sign chart

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/runtime/update-runtime-job.yaml, charts/cf-runtime/values.yaml
=> feat: add env map to runtime patch hook

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/volume-provisioner/daemonset.yaml, charts/cf-runtime/values.yaml
=> fix: dind-lv-monitor securty context for openshift 

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/other/external-secrets.yaml, charts/cf-runtime/templates/runner/secret.yaml, charts/cf-runtime/templates/runtime/secret-dind-certs.yaml
=> feat: add external-secrets template

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/hooks/cm-update-runtime.yaml, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/tests/runtime/runtime_values.yaml, charts/cf-runtime/values.yaml
=> feat: convert pvcs to dict

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/tests/runtime/runtime_test.yaml, charts/cf-runtime/tests/runtime/runtime_values.yaml
=> feat: fix userenvvars

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/other/podMonitor.yaml, charts/cf-runtime/templates/other/serviceMonitor.yaml, charts/cf-runtime/values.yaml
=> feat: add serviceMonitor and podMonitor

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/_components/event-exporter/_deployment.yaml, charts/cf-runtime/templates/_components/event-exporter/_env-vars.yaml, charts/cf-runtime/templates/_components/event-exporter/_helpers.tpl, charts/cf-runtime/templates/_components/event-exporter/_rbac.yaml, charts/cf-runtime/templates/_components/event-exporter/_service.yaml, charts/cf-runtime/templates/_components/event-exporter/_serviceMontor.yaml, charts/cf-runtime/templates/event-exporter/deployment.yaml, charts/cf-runtime/templates/event-exporter/rbac.yaml, charts/cf-runtime/templates/event-exporter/service.yaml, charts/cf-runtime/values.yaml
=> feat: add event-exporter

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> Security vulns

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/files/reconcile-runtime.sh, charts/cf-runtime/templates/_components/runner/_deployment.yaml, charts/cf-runtime/templates/_components/runner/_rbac.yaml, charts/cf-runtime/templates/_components/runner/environment-variables/_sidecar-container.yaml, charts/cf-runtime/templates/hooks/post-install/cm-update-runtime.yaml, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/tests/private-registry/private_registry_test.yaml, charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml, charts/cf-runtime/tests/runtime/runtime_test.yaml, charts/cf-runtime/tests/runtime/runtime_values.yaml, charts/cf-runtime/values.yaml
=> feat: add sidecar container

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/_components/monitor/_rbac.yaml
=> fix: monitor rbac

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/files/cleanup-runtime.sh, charts/cf-runtime/templates/hooks/pre-delete/job-cleanup-resources.yaml
=> fix: delete agent and dind secrets

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/values.yaml
=> chore: update README

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/values.yaml
=> fix: add missing cf-app-proxy in runtime spec

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md
=> fix: update cf-common lib

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This updates dind image in order to fix security vulnerabilities.
Security concerns.
—
=> Update `dind` v20.10.24-1.27.0 → v24.0.6-1.28.2

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> update default runtime CF_DOCKER_* images

.github/workflows/pr-title.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> fix: cf-docker-builder

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This updates `dind` image to the latest available version that contains some vulnerability fixes.
Security concerns.
—
=> build: update `dind` v24.0.6-1.28.2 → v24.0.6-1.28.3

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/_components/volume-provisioner/_env-vars.yaml, charts/cf-runtime/templates/volume-provisioner/deployment.yaml, charts/cf-runtime/tests/volume-provisioner/volume-provisioner_test.yaml
Fix templates to mount `/etc/kubernetes/azure.json` in dvp
=> fix: volume-provisioner with azure disks

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> fix: missing runtime images

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades `engine` to v1.168.1.
Security concerns.
—
=> build: upgrade `engine` to v1.168.1

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
Update kubectl and cf-k8s-agent image for multiarch
=> fix(cf-runtime): fix images for arm

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> feat(engine and cf-git-cloner): improve engine logs and fix shallow fetch

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades the engine to v1.169.8 with fix for pipeline debug mode.
Bug fix.
—
=> build: upgrade engine to v1.169.8

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades `dind` to 25.0.4-1.28.5 with fixes to some CVE.
Security reasons.
—
=> build: upgrade `dind` to 25.0.4-1.28.5

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades the `engine` to the most recent version with performance improvements of compose images pull.
—
—
=> build: upgrade `engine`

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/_components/volume-provisioner/_env-vars.yaml, charts/cf-runtime/templates/_components/volume-provisioner/_secret.yaml
Fix typo in secret volume (dind-volume-provisioner) when gcedisk is enabled.
Update README for gcedisk.
Fix google-service-account.json key in volume-provisioner secret template.
=> fix: serviceAccountJsonSecretKeyRef for gcedisk

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades `dind` to the recent version that contains fixes for some known vulnerabilities.
—
—
=> build: upgrade `dind` to v26.1.4-1.28.7

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This reverts version 6.3.37 since it caused regressions.
—
—
=> build: revert latest version

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/README.md.gotmpl, charts/cf-runtime/templates/runtime/runtime-env-spec-tmpl.yaml, charts/cf-runtime/values.yaml
=> fix: missing annotations for PV

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
updated dind-volume-provisioner image to `1.35.0`
security volnuerability fixes - https://github.com/codefresh-io/dind-volume-provisioner/pull/93
=> fix(sec): fix dind-volume-provisioner security vulnerabilities

charts/cf-runtime/.ci/values-ci.yaml, charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/app-proxy/deployment.yaml, charts/cf-runtime/templates/app-proxy/ingress.yaml, charts/cf-runtime/templates/app-proxy/rbac.yaml, charts/cf-runtime/templates/app-proxy/service.yaml, charts/cf-runtime/templates/event-exporter/deployment.yaml, charts/cf-runtime/templates/event-exporter/rbac.yaml, charts/cf-runtime/templates/event-exporter/service.yaml, charts/cf-runtime/templates/monitor/deployment.yaml, charts/cf-runtime/templates/monitor/rbac.yaml, charts/cf-runtime/templates/monitor/service.yaml, charts/cf-runtime/templates/runner/deployment.yaml, charts/cf-runtime/templates/runner/rbac.yaml, charts/cf-runtime/templates/volume-provisioner/cronjob.yaml, charts/cf-runtime/templates/volume-provisioner/daemonset.yaml, charts/cf-runtime/templates/volume-provisioner/deployment.yaml, charts/cf-runtime/templates/volume-provisioner/rbac.yaml, charts/cf-runtime/templates/volume-provisioner/secret.yaml, charts/cf-runtime/templates/volume-provisioner/storageclass.yaml, charts/cf-runtime/values.yaml
=> fix: fullnameoverride

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, scripts/generate-changelog.sh
=> feat: add changelog

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, scripts/get-all-images.sh
=> fix: get-all-images script

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
This upgrades `venona` to the latest version with security fixes.
=> build: upgrade `venona`

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> chore(CR-27558): updated kubectl

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/templates/_components/ballast/_deployment.yaml, charts/cf-runtime/templates/_components/ballast/_helpers.tpl, charts/cf-runtime/templates/ballast/deployment.yaml, charts/cf-runtime/templates/ballast/priority-class.yaml, charts/cf-runtime/values.yaml
=> feat: add ballast

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/files/patch-runtime.sh
=> fix: modify accounts function

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
=> feat(dind): Add docker daemon metrics endpoint to default configuration

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/tests/private-registry/private_registry_test.yaml, charts/cf-runtime/tests/runtime/runtime_onprem_test.yaml, charts/cf-runtime/tests/runtime/runtime_test.yaml, charts/cf-runtime/values.yaml
=> feat(dind): add CLEAN_DOCKER env var

charts/cf-runtime/Chart.yaml, charts/cf-runtime/README.md, charts/cf-runtime/values.yaml
It's not multi-arch and will crash-loop on ARM
=> fix: pin event-exporter to the correct architecture
